### ISSUE TITLE
Unable to compare list ignoring the order.

### ISSUE THREAD

**Issue by anuragnair03** [ValeraT1982/ObjectsComparer#14]
`list a = {1,2,3};
list b = {3,2,1};`

On comparing the above two list it gets added as a ValueMismatch difference. Is this expected.
Can you please suggest any work-around for ignoring the order of list.

Thanks in advance!

**Comment by ValeraT1982** [comment]
@anuragnair03, thank you for asking. This is expected behavior. You can write custom comparer for you list like in **Example 4: Custom comparer for list**
Please let me know if you have any questions.
