### ISSUE TITLE
Same DateTime property value is being returned under differences

### ISSUE THREAD

**Issue by abhishekkandi** [ValeraT1982/ObjectsComparer#20]
![image](https://user-images.githubusercontent.com/30003726/103679329-b682eb80-4faa-11eb-99c1-978696524813.png)
![image](https://user-images.githubusercontent.com/30003726/103679423-d0243300-4faa-11eb-9618-0ca0128dfbd9.png)
![image](https://user-images.githubusercontent.com/30003726/103679505-eaf6a780-4faa-11eb-8235-ab24b1d681e4.png)

**Comment by ValeraT1982** [comment]
@abhishekkandi, I think it's because values are actually different. You call GetSample1Data() 2 times (which calls DateTime.UtcNow 2 times). Values have the same string representation, but the second one must be bigger by several milliseconds.

**Comment by abhishekkandi** [comment]
Right, Makes sense.
