### ISSUE TITLE
Add Dupe value Comparer

### ISSUE THREAD

**Issue by vbjay** [ValeraT1982/ObjectsComparer#21]
Add a comparer that allows you to specify members to compare and find duplicate values.

Example:

```c#
class SomeData
{
    string FirstName{get;set;}
    string NickName{get;set;}
    string LastName{get;set;}
}
SomeData d = new SomeData(){
    FirstName ="Jim",
    NickName ="The JimSter",
    LastName ="Jim"
}
```
This comparer would say you have duplicates between FirstName and LastName if those members were included in the items.

**Comment by ValeraT1982** [comment]
@vbjay, can you please tell more about your usecase?
