### ISSUE TITLE
DateTime? difference MemberPath returns PropertyName.Value

### ISSUE THREAD

**Issue by cotepatrice** [ValeraT1982/ObjectsComparer#27]
Hi! 

I tried comparing 2 Nullable DateTime. The comparison goes well, but in the "Differences" list, I get "MyPropertyName.Value" instead of just "MyPropertyName" in MemberPath.

You can easily reproduce this behavior by modifying TestClass.A. Change DateTimeProperty type for DateTime?. After that, you can use the ComparerTests.PropertyInequality to see the behavior by looking at the differences received from the CalculateDifferences call. 

Do you think it would be possible to return the real property name here?

**Comment by ValeraT1982** [comment]
Behavior you described is "by design". As I remember nullable types are structs with property "Value". It's what you see in the path.

**_Do you think it would be possible to return the real property name here?_** I don't think it's possible, but you can remove ".Value" from the MemberPath string
