### ISSUE TITLE
.Net core Compatibility

### ISSUE THREAD

**Issue by rsaeed-volvocars** [ValeraT1982/ObjectsComparer#32]
Is it compatible for .Net Core 3.x and will it be supported for higher versions of .Net core e.g. 5.x or 6.x ?

**Comment by ValeraT1982** [comment]
Yes. Package has .NETStandard 1.6, 20, and 2.1 builds.  .Net Core 3.0 uses .NETStandard 2.1 (https://docs.microsoft.com/en-us/dotnet/standard/net-standard) and as I know it's OK to reference lower versions

Yes. I'm planning to support high versions in the future.
