### ISSUE TITLE
Is ObjectsComparer stateless?

### ISSUE THREAD

**Issue by t03apt** [ValeraT1982/ObjectsComparer#33]
Hi!
Is ObjectsComparer stateless? Can I use each comparer as singleton? Should I worry about reusing the same instance cross threads?

**Comment by ValeraT1982** [comment]
No. Comparer has some [properties](https://github.com/ValeraT1982/ObjectsComparer/blob/master/ObjectsComparer/ObjectsComparer/BaseComparer.cs#L13-L25). It's not safe to use one instance of comparer across multiple threads.
