### ISSUE TITLE
The comparison of null values to String.empty is not explicit

### ISSUE THREAD

**Issue by HZ-GeLiang** [ValeraT1982/ObjectsComparer#39]
I have two objects

![image](https://user-images.githubusercontent.com/16562680/162375776-ae800003-e5d3-4d00-9e4e-876c7b8ebcca.png)

I can't tell the difference between value1 and value 2 from the prompt because one value is null and the other is stirm.empty

![image](https://user-images.githubusercontent.com/16562680/162384475-6178e804-6fec-4b1a-a195-a773123db69d.png)

![image](https://user-images.githubusercontent.com/16562680/162378808-4ffa1452-256a-4cac-b407-e3cec681d16e.png)

**Comment by ValeraT1982** [comment]
Yes. Null is represented as empty string. How would you expect to represent 'nothing' as a string?

**Comment by HZ-GeLiang** [comment]
I looked at the source code and found that Difference overrides the stirng method.
If I wanted to customize the prompt message, I would not get Null value while iterating over differences
