### ISSUE TITLE
Comparing expandoObject deserialized via JsonSerializer does not work

### ISSUE THREAD

**Issue by masherak** [ValeraT1982/ObjectsComparer#43]
Helo, if I use deserialization method from class JsonSerializer and namespace: System.Text.Json so comparing end with zero differences everytime. If I use newtonsoft - JsonConvert it is working well.

**Comment by ValeraT1982** [comment]
Can you please give an example?

**Comment by masherak** [comment]
namespace: System.Text.Json
<img width="746" alt="image" src="https://user-images.githubusercontent.com/15813908/172206318-3eca0764-7cb0-449e-b285-c47a0a32db5a.png">

**Comment by ValeraT1982** [comment]
What framework do you use? What version of the JsonSerializer package?
Line 
`var deserializedValue1 = System.Text.Json.JsonSerializer.Deserialize<ExpandoObject>("JSON");`
throws an exception because "JSON" isn't a valid JSON.

**Comment by masherak** [comment]
It is actual version of .NET 6

**Comment by masherak** [comment]
Yes "JSON" is really not valid JSON just replace it with some JSON with one field and you will se that it is not work.

**Comment by ValeraT1982** [comment]
Please provide working code example, result and result you expect.

**Comment by masherak** [comment]
var testObject1 = new
		{
			A = "ABC",
			B = "CBA"
		};

		var testObject2 = new
		{
			A = "CBA",
			B = "ABC"
		};

		var testJson1 = JsonSerializer.Serialize(testObject1);

		var testJson2 = JsonSerializer.Serialize(testObject2);

		Console.WriteLine($"testJson1: {testJson1}");
		Console.WriteLine($"testJson2: {testJson2}");

		var comparer = new Comparer(new ComparisonSettings { UseDefaultIfMemberNotExist = true });

		var deserializedValue1 = JsonSerializer.Deserialize<ExpandoObject>(testJson1);

		var deserializedValue2 = JsonSerializer.Deserialize<ExpandoObject>(testJson2);

		comparer.Compare (deserializedValue1, deserializedValue2, out var configurationDifferences);

		Console.WriteLine($"Count: {configurationDifferences.Count()}, Changes: {string.Join(',', configurationDifferences.Select(_ => $"{_.Value1} => {_.Value2}"))}");

**Comment by masherak** [comment]
<img width="351" alt="image" src="https://user-images.githubusercontent.com/15813908/174629767-e46c6f89-e58c-4107-8d32-3efa4a5e666b.png">

**Comment by masherak** [comment]
With JsonSerializer you can see 0 changes, with JsonConvert it is work well.

**Comment by ValeraT1982** [comment]
Now I see the problem. 
System.Text.Json.JsonSerializer.Deserialize<ExpandoObject>(obj); returns Expando object and each property type is System.Text.Json.JsonElement. System.Text.Json.JsonElement has only 2 properties:
```
     public JsonElement this[int index] { get; }
     public JsonValueKind ValueKind { get; }
```

Only these 2 properties are used by comparer. It's why comparer says that objects are equal.
As a solution, you can create a custom comparer for System.Text.Json.JsonElement and use Factory (https://github.com/ValeraT1982/ObjectsComparer#factory). 
I'll be considering fixing it in the next version.

**Comment by masherak** [comment]
Ok, thank you very much, have a nice day.
