### ISSUE TITLE
Members of type object are not taken into account

### ISSUE THREAD

**Issue by BAV0** [ValeraT1982/ObjectsComparer#48]
**Issue:**
When comparing 2 objects of the same class, which has a member of type _object_, this member's value (or type for that matter) is not taken into account.

**Example:** ([.NET Fiddle](https://dotnetfiddle.net/n09eIU))
```
public class Model {
	public object Prop1 { get; set; }
}

var o1 = new Model { Prop1 = "string" };
var o2 = new Model { Prop1 = "other string" };

var comparer = new ObjectsComparer.Comparer<Model>();
var result = comparer.Compare(o1, o2, out var _);

Console.WriteLine(result); // Should be false
```

**Workaround:** ([.NET Fiddle](https://dotnetfiddle.net/Km5pvY))
A possible workaround is to override the comparison for _object_-type members: 
```
comparer.AddComparerOverride<object>(new ObjectValueComparer());

public class ObjectValueComparer : IValueComparer
    {
        public bool Compare(object o1, object o2, ComparisonSettings settings)
        {
            if (o1.GetType() != o2.GetType())
            {
                return false;
            }

            return new Comparer().Compare(o1.GetType(), o1, o2);
        }

        public string ToString(object value)
        {
            return value.ToString();
        }
    }
```

**Comment by ValeraT1982** [comment]
It'a an expected behavior. Comparer "looks" at the type of the property to get the list of the members.

More details [here](https://github.com/ValeraT1982/ObjectsComparer/issues/6)
