### ISSUE TITLE
Compare always returns true (is equal)?

### ISSUE THREAD

**Issue by tekeroth-snapcode** [ValeraT1982/ObjectsComparer#56]
I might have missed something important, but this does not seem to work at all for me?

The Compare method seems to return true (is equal) all the time, regardless if they objects are different or not. Here are two screenshots that shows this:

![image](https://github.com/ValeraT1982/ObjectsComparer/assets/104069264/ca75f040-07a8-4956-b864-7adc429b525d)
In the image above, we can see that `firstObject.IsReturnBooking` is `true`, and `secondCopy.IsReturnBooking` is `false`.

If I then step one more line, and look at the `isEqual` and `differences`, they show that the objects are equal, no changes detected:

![image](https://github.com/ValeraT1982/ObjectsComparer/assets/104069264/f60a0dff-846d-4e4f-bc4e-bf6b25e26867)

I am running .NET 7 in Visual Studio 2022, version of lib used is 1.4.1

**Comment by ValeraT1982** [comment]
Can you please provide the definition of Booking?

To troubleshoot you can:
1. Create 2 bookings and try to compare them (no deserialization).
2. If the previous step works, create 2 JSON files with different bookings, deserialize and try to compare (no random property changes)

Try to create a minimal example that returns true when objects are different and include all code of that example.

**Comment by wexman** [comment]
I have a similar issue with a relatively simple object graph using the default settings. A difference two or three levels down is not detected. Is this project still alive? If so, I would create an example...

**Comment by wexman** [comment]
fwiw, here's simple test that fails:

``` c#
    [TestFixture]
    public class DesiredStateChecks
    {
        public abstract class DataSource{}
        
        public class DbDataSource : DataSource
        {
            public string CommandText { get; set; }
        }
        
        public class ReportConfig
        {
            public string Name { get; set; }
            public DataSource Source { get; set; }
        }
        
        [Test]
        public void Comparer()
        {
            var ReportsA = new ReportConfig()
            {
                Name = "SomeReport",
                Source = new DbDataSource()
                {
                    CommandText = @"url(§templateDir§)\SomeQuery.sql"
                }
            };
            var ReportsB = new ReportConfig()
            {
                Name = "SomeReport",
                Source = new DbDataSource()
                {
                    // no CommandTextHere - that should be a difference!
                }
            };
            ObjectsComparer.Comparer comparer = new Comparer();

            var areEqual = comparer.Compare(ReportsA, ReportsB, out var differences);

            Assert.That(areEqual, Is.False);
        }
    }
```

That is, and I'm sorry to say so, rather disappointing for an object comparison library. But I'm not complaining, I'm trying to help.

**Comment by wexman** [comment]
Found out that if i declare ReportConfig.Source to be of type DbDataSource (instead of the abstract DataSource base class), then it'll work as expected, so it seems it has to do something with polymorphism.

**Comment by ValeraT1982** [comment]
It is an expected behavior. If a property has the type DataSource, only properties from this type are compared. 
More [here](https://github.com/ValeraT1982/ObjectsComparer/issues/6).

**Comment by wexman** [comment]
Ok, so it'll claim two objects equal that are totally not. I understand it's a design decision,  but I fail to see in which universe this would make sense.
