### ISSUE TITLE
Comparer returns true for different items after cast

### ISSUE THREAD

**Issue by maksim-shila** [ValeraT1982/ObjectsComparer#6]
class Item
        {
            public string Name { get; set; }
        }

        [Test]
        public void ItemsDifferent_ReturnsFalse()
        {
            var item1 = new Item {Name = "First Item"};
            var item2 = new Item {Name = "Second Item"};

            var comparer = new Comparer();
            Assert.False(comparer.Compare((object)item1, item2));
        }

This test fails. Doesn't looks like expected behabior
If remove cast to object test passed

**Comment by ValeraT1982** [comment]
It is expected behavior because if you cast one of the items to the object than items will be compared with each other as an objects (object doesn't have Name property, co this property is skipped during comparison).

Lets look at the example. 
```
class A
{
    Name { get: set; }
}
```

```
class B: A
{
    Description { get: set; }
}
```

```
var b1 = = new B() { .... };
var b2 = = new B() { .... };

// compare objects as B (Name and Description) 
var result = comparer.Compere(b1, b2);

// compare objects as A (Name only) 
var result = comparer.Compere((A)b1, b2);
```

It allows you to have more control.

**Comment by maksim-shila** [comment]
For me it looks like a feature, not default behavior.
Even you cast B object to A, you not change object type - it still B. 
Anyway, your project your rules =)
Thanks)
