### ISSUE TITLE
Compare does not comparing subclass with same type

### ISSUE THREAD

**Issue by andreiackowski** [ValeraT1982/ObjectsComparer#8]
In the sample below the comparer.Compare method is just comparing the first level of object, and is not considering the levels 2 and 3 of the object.

            var a1 = new ClassA { StringProperty = "String", IntProperty = 1 ,
            SubClass = new ClassA
            {
                IntProperty = 2,
                SubClass = new ClassA
                {

                    IntProperty = 3
                }
            }};

            var a2 = new ClassA { StringProperty = "String", IntProperty = 4 };
            var comparer = new ObjectsComparer.Comparer<ClassA>(new ComparisonSettings
            {
                RecursiveComparison = true,
                EmptyAndNullEnumerablesEqual = true,
            });

            var isEqual = comparer.Compare(a1, a2, out var differences);

            //Print results
            Console.WriteLine(isEqual ? "Objects are equal" : string.Join(Environment.NewLine, differences));

Subobjects differences are not shown instead of this is showed a string.
![image](https://user-images.githubusercontent.com/15099639/57331756-c3717c80-70ef-11e9-9102-d07d52a5015d.png)

**Comment by ValeraT1982** [comment]
For object a1 SubClass property has a value, for object a2 SubClass property is null. 
If custom comparer is not not specified for ClassA then ToString() method is used to get a value (in this case it's "ConcoleApp6.ClassA", by default ToString() returns full name of the class). 
It looks correct.
If two properties are being compared and one property has a value (not null) when another one doesn't (null) then recursion stops.

**Comment by andreiackowski** [comment]
Makes sense thank you.
